  
version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    tty: true
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    environment:
      DOMAINS: 'ec2-54-64-51-76.ap-northeast-1.compute.amazonaws.com -> http://web:5000'