  
version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    tty: true
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0